### ISSUE TITLE
inconsistencies in version ids

### ISSUE THREAD

**Issue by SpaceWalkerRS** [skyrising/mc-versions#5]
This concerns versions that were re-uploaded. There seems to be no consistent 'format' for the ids of these versions.
- Some version ids copy the omniarchive id
  - `server-c1.4` re-upload -> `server-c1.4-1327`
  - `server-a0.1.1` re-upload -> `server-a0.1.1-1707`
  - `a1.2.0_02` (launcher) -> `a1.2.0_02-launcher`
  - `server-a0.2.5` -> `server-a0.2.5-0923`
  - `server-a0.2.5` re-upload -> `server-a0.2.5-1004`
  - `b1.3` -> `b1.3-1647` (while the first re-upload follows the incremental suffix format)
  - `b1.3` second re-upload -> `b1.3-1731` (while the first re-upload follows the incremental suffix format)
  - `b1.9-pre4` -> `b1.9-pre4-1425`
  - `b1.9-pre4` first re-upload -> `b1.9-pre4-1435`
  - `b1.9-pre4` second re-upload -> `b1.9-pre4-1440` (which also has a dead download link, since the omniarchive version is `b1.9-pre4-1441`)
  - `12w05a` -> `12w05a-1354`
  - `12w05a` re-upload -> `12w05a-1442`
  - `13w03a` first re-upload -> `13w03a-1538`
  - `13w03a` second re-upload -> `13w03a-1647`
  - `13w05a` -> `13w05a-1504`
  - `13w05a` re-upload -> `13w05a-1538`
  - `13w06a` -> `13w06a-1559`
  - `13w06a` re-upload -> `13w06a-1636`
  - `1.5.2-pre` re-upload -> `1.5.2-pre-250903`
- Some version ids have a number suffix that increments for every re-upload. There are also inconsistencies in whether the original gets a suffix, and whether the first re-upload gets suffix `-1` or `-2`.
  - `c0.0.19a_06` re-upload -> `c0.0.19a_06-2`
  - `a1.0.13_01` -> `a1.0.13_01-1`
  - `a1.0.13_01` re-upload -> `a1.0.13_01-2`
  - `a1.0.14`-> `a1.0.14-1`
  - `a1.0.14` re-upload (launcher) -> `a1.0.14`
  - `a1.0.14` re-upload -> `a1.0.14-2`
  - `a1.1.0` -> `a1.1.0-1`
  - `a1.1.0` (launcher, supposedly a pre-re-upload version) -> `a1.1.0`
  - `a1.1.0` re-upload -> `a1.1.0-2`
  - `b1.1` re-upload -> `b1.1-2`
  - `b1.3` first re-upload -> `b1.3-1` (while the pre-re-upload and second re-upload follow the omni-id format)
  - `b1.8-pre1` -> `b1.8-pre1-1`
  - `b1.8-pre1` re-upload -> `b1.8-pre1-2`
  - `b1.9-pre3` re-upload -> `b1.9-pre3-2`
  - `1.0.0-rc2` -> `1.0.0-rc2-1`
  - `1.0.0-rc2` first re-upload -> `1.0.0-rc2-2`
  - `1.0.0-rc2` second re-upload -> `1.0.0-rc2-3`
  - 
- Some version ids are not unique
  - `a1.0.4` and `a1.0.4-launcher` on omniarchive both get id `a1.0.4` in mc-versions
  - `b1.2_02` and `b1.2_02-launcher` on omniarchive both get id `b1.2_02` in mc-versions
  - `b1.4-1507` and `b1.4-1634` on omniarchive both get id `b1.4` on mc-versions

Additionally there are some version ids that appear wrong, but I might be mistaken here.
- `inf-20100617-2` and `inf-20100617-3` should be `inf-20100617-1` and `inf-20100617-2` respectively.

**Comment by skyrising** [comment]
All ids in mc-versions are based on omniarchive as much as possible (sometimes client and servers are a few minutes apart, omniarchive tracks them separately and mc-versions only assigns a single id to both)

> Some version ids have a number suffix that increments for every re-upload. There are also inconsistencies in whether the original gets a suffix, and whether the first re-upload gets suffix -1 or -2

That's incorrect, at least for the first couple you list (I haven't checked them all). mc-versions calls those `c0.0.19a_06-0137`, `a1.0.13_01-1038`, `a1.0.13_01.1444`, etc.
I suppose you're going by the file name of the jar?

> Some version ids are not unique
> a1.0.4 and a1.0.4-launcher on omniarchive both get id a1.0.4 in mc-versions

No, mc-versions has both

> b1.2_02 and b1.2_02-launcher on omniarchive both get id b1.2_02 in mc-versions

mc-versions has both, but looks like the url for the `b1.2_02` JAR incorrectly points to the launcher one as well

> b1.4-1507 and b1.4-1634 on omniarchive both get id b1.4 on mc-versions

mc-versions has both and points to betacraft/archive.org for -1507 and to mojang for -1634

**Comment by SpaceWalkerRS** [comment]
I was going off a copy of the manifest json in my gradle cache somewhere. I suppose it's been there for a long time at this point, and has some outdated information? I double checked all the cases I listed, they do occur that way in my copy of the manifest. I'll redownload the manifest and re-assess.

**Comment by SpaceWalkerRS** [comment]
Hmm I am still seeing the same issues. In case it helps, I downloaded the manifest from (https://skyrising.github.io/mc-versions/version_manifest.json), but I can also see them in the [repo](https://github.com/skyrising/mc-versions/blob/main/data/version_manifest.json). For example:
- [`c0.0.19a_06-0137`](https://github.com/skyrising/mc-versions/blob/d6aee852110cad9202f4827aaa00cc7e7749388f/data/version_manifest.json#L8240)
- [`b1.4-1634`](https://github.com/skyrising/mc-versions/blob/d6aee852110cad9202f4827aaa00cc7e7749388f/data/version_manifest.json#L6853)
- [`b1.4-1507`](https://github.com/skyrising/mc-versions/blob/d6aee852110cad9202f4827aaa00cc7e7749388f/data/version_manifest.json#L6862)

**Comment by SpaceWalkerRS** [comment]
It looks like in the main manifest the version ids do not match the version ids listed in the version specific manifests. For example b1.4-1507 [main manifest](https://github.com/skyrising/mc-versions/blob/d6aee852110cad9202f4827aaa00cc7e7749388f/data/version_manifest.json#L6862) vs [version specific manifest](https://github.com/skyrising/mc-versions/blob/d6aee852110cad9202f4827aaa00cc7e7749388f/data/version/manifest/b1.4-1507.json#L28)

**Comment by skyrising** [comment]
Yes, the main manifest lists both `id` and `omniId`. The idea behind that was that the `id` would match `id` in the version specific manifest (`data/manifest/...`, since that would be coming from Mojang).
Since the introduction of generated version specific manifests (`data/version/manifest/...`) it would probably make sense to use the omni/mc-versions id in the main manifest `id` as well.

**Comment by SpaceWalkerRS** [comment]
it would probably for the best, since afaik tools like Loom parse versions from the manifest through these ids

**Comment by SpaceWalkerRS** [comment]
on the other hand we'll get versions like 1.3 and 13w36a which will get really ugly ids like `1.3-pre-07261249` and `13w36a-09051446` which makes them hard to use also - it's just that at the moment the ids are not unique which is a bit problematic
